#sensors:
#sensors:
#    resource: "@SensorsBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@SensorsBundle/Controller/DefaultController.php"
    type:     annotation


home:
    path:  /
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }
credits:
    path:  /credits
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }
contact:
    path:  /contact
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }

sensors_data_send:
    path:  /push
    defaults: { _controller: SensorsBundle:Default:push }


stations:
    type:     rest
    resource: FAb\SensorsBundle\Controller\API\StationController

#datalines:
#    type:     rest
#    resource: FAb\SensorsBundle\Controller\API\DatalineController
#

crud_station:
    resource: "@SensorsBundle/Controller/CRUD/StationController.php"
    type:     annotation

crud_dataline:
    resource: "@SensorsBundle/Controller/CRUD/DatalineController.php"
    type:     annotation



#app:
#    resource: "@AppBundle/Controller/"
#    resource: "@GeoBiduleBundle/Resources/config/routing.yml"
#    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"