sensors:
    resource: "@SensorsBundle/Controller/"
    type:     annotation
    prefix:   /

geo_bidule:
    resource: "@GeoBiduleBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    resource: "@GeoBiduleBundle/Resources/config/routing.yml"
#    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    