sensors:
    resource: "@SensorsBundle/Controller/"
    type:     annotation
    prefix:   /

sensors_data_send:
    path:  /push
    defaults: { _controller: SensorsBundle:Default:push }


#app:
#    resource: "@AppBundle/Controller/"
#    resource: "@GeoBiduleBundle/Resources/config/routing.yml"
#    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"    