sensors:
    resource: "@SensorsBundle/Controller/"
    type:     annotation
    prefix:   /

home:
    path:  /
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }
credits:
    path:  /credits
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }
contact:
    path:  /contact
    defaults: { _controller: SensorsBundle:Default:index }
    options: { i18n: false }

sensors_data_send:
    path:  /push
    defaults: { _controller: SensorsBundle:Default:push }


#app:
#    resource: "@AppBundle/Controller/"
#    resource: "@GeoBiduleBundle/Resources/config/routing.yml"
#    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"