<?php

namespace FAb\SensorsBundle\Repository;

/**
 * DatalineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatalineRepository extends \Doctrine\ORM\EntityRepository
{
}
