<?php

namespace FAb\SensorsBundle\Repository;

/**
 * DatasetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasetRepository extends \Doctrine\ORM\EntityRepository
{
}
